import './globals.css'
import { Oxygen } from 'next/font/google'
import Link from 'next/link'
import { MdOutlineHome } from "react-icons/md"
import { CiBoxList } from "react-icons/ci";

const oxygen = Oxygen({
  subsets: ['latin'],
  weight: '400'
})

export const metadata = {
  title: 'NextJS Todo App',
  description: 'Generated by create next app',
}

const links = [
  { href: '/', label: 'Home', icon: <MdOutlineHome /> },
  { href: '/todos', label: 'Todos', icon: <CiBoxList /> },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${oxygen.className} bg-stone-100`}>
        <div className="grid grid-cols-[200px_auto] h-[100vh]">
          <header>
            <nav>
              <ul className="flex flex-col gap-4 m-auto mt-2 rounded-lg p-4">
                {links.map((link, i) => (
                  <li className="text-md flex gap-2 items-center justify-start text-gray font-semibold" key={i}>
                    {link.icon} <Link href={link.href}>{link.label}</Link>
                  </li>
                ))}
              </ul>
            </nav>
          </header>
          <div className="bg-white rounded-lg ml-4 mt-4 shadow-lg">{children}</div>
        </div>
      </body>

    </html>
  )
}

